name: Build & Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.x  # 或更低版本，如 14.x

      - name: Install dependencies
        run: yarn install --frozen-lockfile;

      - name: Test
        run: |
          yarn test;

      - name: Build
        run: |
          yarn build;

      - name: Archive dist folder
        run: tar -czvf dist.tar.gz dist/

      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist.tar.gz
